#!/bin/sh

ip=$(ip -f inet -o a s | grep -v 127.0.0.1 | awk '{gsub(/\/.*/, "", $4);print $4; exit}')

cat <<dog > /config.jcl
bind_addr = "0.0.0.0"
data_dir = "/data"

advertise {
  # We need to specify our host's IP because we can't
  # advertise 0.0.0.0 to other nodes in our cluster.
  rpc = "$ip:4647"
}

server {
  enabled = true
}
dog
